services:
  - type: web
    name: pudge-wars
    env: node
    buildCommand: npm install --production
    startCommand: node server.js
    plan: free
    region: frankfurt
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8080
      - key: DISABLE_YARN
        value: "true"
