services:
  - type: web
    name: pudge-wars
    env: node
    buildCommand: yarn install
    startCommand: node server.js
    plan: free
    region: frankfurt
    healthCheckPath: /health
    healthCheckTimeout: 30
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8080
